In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [84]:
# Create two random-integer vectors
n = 4
v1 = np.round(15*np.random.randn(n))
v2 = np.round(15*np.random.randn(n))
print(v1,v2)

[ 5. -0. -7.  7.] [11.  4.  3. 29.]


In [85]:
# Compute the length of the two vectors
mag1 = np.linalg.norm(v1)
mag2 = np.linalg.norm(v2)

# Another way to compute the magnitude of the vectors
# mag1 = np.sqrt(np.dot(v1,v1))
# mag2 = np.sqrt(np.dot(v2,v2))

# Compute the dot product and its magnitude of the two vectors

dps_mag = np.abs(np.dot(v1,v2)) 

# "Normalize" the vectors

# First way is finding mu and multiplying by vector
mu1 = 1 / mag1
mu2 = 1 / mag2

v1_unit = v1*mu1
v2_unit = v2*mu2

# Second way is multiplying vector by its magnitude directly
v1u = v1/mag1
v2u = v2/mag2

# Compute the magnitud of the dot product of the two normalized vectors
dps_norm_vecs = np.abs(np.dot(v1_unit,v2_unit))

print(v1,v2)
print(mag1,mag2,dps_mag)
print(' ')
print(v1_unit,v2_unit)
print(dps_norm_vecs)
print(' ')
print(np.linalg.norm(v1_unit))
print(np.linalg.norm(v2_unit))
print(np.dot(v1_unit,v1_unit))
print(np.dot(v2_unit,v2_unit))

[ 5. -0. -7.  7.] [11.  4.  3. 29.]
11.090536506409418 31.416556144810016 237.0
 
[ 0.45083482 -0.         -0.63116874  0.63116874] [0.35013386 0.1273214  0.09549105 0.92308017]
0.6802009183666802
 
1.0
0.9999999999999999
1.0
0.9999999999999999


In [36]:
v1 = np.array([ 1, 2])
v1l = np.linalg.norm(v1)
print(v1l)

2.23606797749979
