In [1]:
import numpy as np

### Sherman-Morrison inverse

In [9]:
m = 4
n = 4

a = np.random.randn(m)
b = np.random.rand(m)
idm = np.eye(m)

A = idm-np.outer(a,b)
print(np.outer(a,b))
print(A)

Ainv = idm + np.outer(a,b)/(1-np.dot(a,b))
print(np.round(A@Ainv))

[[ 0.33132413  0.15482111  0.12440536  0.58851424]
 [-0.15133956 -0.07071794 -0.05682488 -0.26881678]
 [-0.02130048 -0.00995329 -0.00799789 -0.03783496]
 [ 0.40326514  0.1884377   0.15141773  0.71629942]]
[[ 0.66867587 -0.15482111 -0.12440536 -0.58851424]
 [ 0.15133956  1.07071794  0.05682488  0.26881678]
 [ 0.02130048  0.00995329  1.00799789  0.03783496]
 [-0.40326514 -0.1884377  -0.15141773  0.28370058]]
[[ 1.  0.  0.  0.]
 [ 0.  1. -0. -0.]
 [-0. -0.  1.  0.]
 [ 0.  0.  0.  1.]]


### Show that A'A = R'R

In [37]:
m = 4

A = np.random.randn(m,m)
idm = np.eye(m)
Q,R = np.linalg.qr(A)

print(A)
print(np.round(Q.T@Q))

print(A.T@A)
print(R.T@R)
print(np.round(A.T@A-R.T@R))

[[-0.45225989 -0.61912231  0.32978554 -0.16256697]
 [ 0.82825134 -0.29956135  0.19693793 -0.65985202]
 [-0.34305571 -0.33493566  0.02009741 -0.77007915]
 [-1.16461328 -1.42676354 -0.61275623  0.07964333]]
[[ 1. -0. -0. -0.]
 [-0.  1. -0. -0.]
 [-0. -0.  1.  0.]
 [-0. -0.  0.  1.]]
[[ 2.36455061  1.80842146  0.72069485 -0.30157444]
 [ 1.80842146  2.62088553  0.60435434  0.44260977]
 [ 0.72069485  0.60435434  0.52341716 -0.24784067]
 [-0.30157444  0.44260977 -0.24784067  1.06119766]]
[[ 2.36455061  1.80842146  0.72069485 -0.30157444]
 [ 1.80842146  2.62088553  0.60435434  0.44260977]
 [ 0.72069485  0.60435434  0.52341716 -0.24784067]
 [-0.30157444  0.44260977 -0.24784067  1.06119766]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -0.  0.]
 [ 0.  0.  0.  0.]]


In [23]:
A = np.round(np.random.rand(4,4),3)
A

array([[0.009, 0.626, 0.122, 0.727],
       [0.14 , 0.336, 0.831, 0.343],
       [0.345, 0.05 , 0.487, 0.666],
       [0.213, 0.488, 0.633, 0.411]])

In [26]:
Q,R = np.linalg.qr(A)
print(Q)
print(Q.T@A)


[[-0.02097708 -0.80998615  0.42846115 -0.39987928]
 [-0.32631019 -0.26728014 -0.83993494 -0.34145614]
 [-0.80412153  0.3618639   0.33301783 -0.33397935]
 [-0.49645764 -0.37621573 -0.00542916  0.78228004]]
[[-4.29039625e-01 -4.05249282e-01 -9.79587841e-01 -8.66763763e-01]
 [ 1.52655666e-16 -7.62357541e-01 -3.82844946e-01 -5.94160330e-01]
 [-9.19403442e-17  2.01661604e-16 -4.86970646e-01  2.42952061e-01]
 [ 5.55111512e-17  5.55111512e-17 -5.55111512e-17 -3.08744843e-01]]
