In [1]:
import numpy as np

In [73]:
# m = 4
# n = 4

A = np.array([[2,3,4],
              [5,6,8],
              [3,1,2]])

B = np.array([[4,2,1],
              [6,3,1],
              [2,1,3]])

print(A[:,0])
print(B[0,:])

[2 5 3]
[4 2 1]


In [76]:
# szA = np.shape(A)
# layers = np.zeros(szA)

# for i in range(szA[0]):
#     layers += np.outer(A[:,i],B[i,:])
    
# print(layers)

# # Implement the matrix multiplication directly
# layers2 = A@B
# print(layers2)

[[34. 17. 17.]
 [72. 36. 35.]
 [22. 11. 10.]]
[[34 17 17]
 [72 36 35]
 [22 11 10]]


In [97]:
m = 3
n = 6

A = np.random.randn(m,n)
print(A)
B = np.random.randn(n,m)
print(B)

[[-0.78150178 -0.0487712   0.8638459   1.29178787  0.3796965   1.26782858]
 [ 0.00214685 -0.54081518 -0.78138886  0.98020255  0.23253613  1.41767935]
 [ 0.05934574  0.87892879 -0.38651861  2.10562206  1.44503773  2.09904622]]
[[-0.799969    1.62586782  0.58634329]
 [ 1.26818868 -0.64007941  0.81329594]
 [ 0.71138081  0.44672078  2.59362582]
 [ 0.59548437 -1.80881537  1.08606242]
 [ 0.42719046  2.26828305 -0.63436146]
 [-1.11083679  0.10399005  1.02416724]]


In [100]:
C = np.zeros((m,m))

for i in range(n):
    C += np.outer(A[:,i],B[i,:])
    
print(C)
C2 = A@B
print(C2)

[[ 0.7009411  -2.19700829  4.20316523]
 [-2.13521601 -1.09753062 -0.09622439]
 [ 0.33168445 -0.95140883  3.26707664]]
[[ 0.7009411  -2.19700829  4.20316523]
 [-2.13521601 -1.09753062 -0.09622439]
 [ 0.33168445 -0.95140883  3.26707664]]


In [84]:
A = np.array([[1,2],
              [3,4],])

B = np.array([[2,4,1],
              [3,1,2]])

A@B


array([[ 8,  6,  5],
       [18, 16, 11]])