In [1]:
import numpy as np

In [ ]:
m = 4
n = 3

A = np.round(6*np.random.randn(m,n))
B = np.round(6*np.random.randn(m,n))

Asym = A@A.T
Bsym = B@B.T

In [26]:
AplusB = Asym + Bsym # symmetric

AB = Asym@Bsym       # non-symmetric 
BA = (Bsym@Asym).T   # non-symmetric

ABhad = Asym*Bsym    # symmetric

print(AB-AB.T)       # AB minus its transpose is equal to a skew-symmetric matrix

[[     0. -13987.   9470.  -2550.]
 [ 13987.      0. -37003.  -4289.]
 [ -9470.  37003.      0.   9487.]
 [  2550.   4289.  -9487.      0.]]


In [11]:
# Testing associative and commutative properties of Hadamard multiplication

m = 5
n = 4

A = np.round(5*np.random.randn(m,n))
B = np.round(5*np.random.randn(m,n))
C = np.round(5*np.random.randn(m,n))

rslt1 = C*(A+B)
rslt2 = C*B + A*C

rslt1 - rslt2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])