In [1]:
import numpy as np

### MCA algorithm to calculate inverse

In [91]:
# Create a random matrix
m = 4
A = np.round(6*np.random.randn(m,m))
det = np.linalg.det(A)
print(A)

[[ -3.  -8.  -3.  -4.]
 [ -9.   5.  -2.  -6.]
 [ -2. -11.   1. -14.]
 [  4.  -7.  -7.   3.]]


In [95]:
# Initialize complementary minors matrix

M = np.zeros((m,m))
H = np.zeros((m,m))

for i in range(0,m):
    for j in range(0,m):
        
        # Eliminate one row each iteration
        rows = [True]*m
        rows[i] = False
        
        # Eliminate one col each iteration
        cols = [True]*m
        cols[j] = False
        
        # Compute complementary minors matrix
        M[i,j] = np.linalg.det(A[rows,:][:,cols])
        H[i,j] = (-1)**(i+j)

# Cofactors matrix
C = M*H

# Adjugate matrix (matriz de adjuntos)
Ainv1 = C.T/det
Ainv2 = np.linalg.inv(A)
print(np.round(Ainv1-Ainv2))
print(A@Ainv1)

[[ 0.  0. -0.  0.]
 [-0.  0.  0.  0.]
 [-0. -0.  0. -0.]
 [-0.  0.  0. -0.]]
[[ 1.00000000e+00 -4.44089210e-16  8.32667268e-17  0.00000000e+00]
 [ 2.22044605e-16  1.00000000e+00  3.33066907e-16  0.00000000e+00]
 [ 1.77635684e-15 -6.80011603e-16  1.00000000e+00  1.11022302e-16]
 [ 2.22044605e-16 -3.33066907e-16 -2.22044605e-16  1.00000000e+00]]


In [21]:
def mdets(a,b,c,d,e,f,g,h,i):
    dets = (a*e*i)+(b*f*g)+(c*d*h)-(c*e*g)-(b*d*i)-(a*f*h)
    return dets

In [92]:
# Compute the complementary matrix
M = np.zeros((m,m))
M[0,0] = mdets(-3,-3,6,-6,5,-2,14,5,7)
M[0,1] = mdets(3,-3,6,0,5,-2,16,5,7)
M[0,2] = mdets(3,-3,6,0,6,-2,16,14,7)
M[0,3] = mdets(3,-3,-3,0,-6,5,16,14,5)
M[1,0] = mdets(2,-0,-5,-6,5,-2,14,5,7)
M[1,1] = mdets(-8,-0,-5,0,5,-2,16,5,7)
M[1,2] = mdets(-8,2,-5,0,-6,-2,16,14,7)
M[1,3] = mdets(-8,2,-0,0,-6,5,16,14,5)
M[2,0] = mdets(2,0,-5,-3,-3,6,14,5,7)
M[2,1] = mdets(-8,-0,-5,3,-3,6,16,5,7)
M[2,2] = mdets(-8,2,-5,3,-3,6,16,14,7)
M[2,3] = mdets(-8,2,-0,3,-3,-3,16,14,5)
M[3,0] = mdets(2,-0,-5,-3,-3,6,-6,5,-2)
M[3,1] = mdets(-8,-0,-5,3,-3,6,0,5,-2)
M[3,2] = mdets(-8,2,-5,3,-3,6,0,-6,-2)
M[3,3] = mdets(-8,2,-0,3,-3,-3,0,-6,5)

# Create cofactor matrix
H = np.array([[1,-1,1,-1],[-1,1,-1,1],[1,-1,1,-1],[-1,1,-1,1]])
C = M*H
# Divide matrix transposed by determinant
det = np.linalg.det(A)
Ainv1 = C.T*(1/det)
Ainv2 = np.linalg.inv(A)
print(Ainv1-Ainv2)

[[ 0.08510638 -0.10253118 -0.13499633 -0.1337124 ]
 [ 0.20983125 -0.06511372 -0.04438738 -0.03209831]
 [-0.15608951  0.182135    0.1201394   0.20506236]
 [-0.01724138  0.23954512  0.17021277  0.11261922]]
