In [1]:
import numpy as np

### Inverse of diagonal matrix

In [57]:
m = 3
A = np.diag([2,1,3])
print(A)
Ainv = np.linalg.inv(A)
print(Ainv)

[[2 0 0]
 [0 1 0]
 [0 0 3]]
[[0.5        0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         0.33333333]]


In [63]:
A = np.random.randn(4,4)
print(A.T@A)

[[ 4.73269858  2.91692495 -1.82964914 -1.54642208]
 [ 2.91692495  7.59858701 -4.55538678  0.14975164]
 [-1.82964914 -4.55538678  3.66127336 -1.68745484]
 [-1.54642208  0.14975164 -1.68745484  3.64842368]]
