In [1]:
import numpy as np

### Reduced-rank matrix via matrix multiplication

In [72]:
m = 4
n = 3
r = 2 # r <= m,n

A = np.round(6*np.random.randn(m,r))
B = np.round(6*np.random.randn(r,n))
# B[:,4:] = 0
# print(np.shape(B))
# print(B)
# print(A)
# print(' ')
# print(A[:, 5:])

# With the matrix mult operation, 'm' define the matrix dimensionality and 'n' define the rank
C = A@B

print(np.linalg.matrix_rank(C))
print(np.shape(C))
print(C)

2
(4, 3)
[[-12.  44.  32.]
 [ -9. -30.  15.]
 [  1.   8.  -1.]
 [ 13.  62. -19.]]


### Scalar multiplication and Rank

In [101]:
m = 6
n = 4
l = .7

F = np.random.randn(m,m)
R = np.random.randn(m,n-1)@np.random.randn(n-1,n)

rankF = np.linalg.matrix_rank(F)
rankR = np.linalg.matrix_rank(R)
rankFl = np.linalg.matrix_rank(F*l)
rankRl = np.linalg.matrix_rank(R*l)
# print(rankF,rankFl,rankR,rankRl)

# Test for rank(l*F) == l*rank(F)
rslt1F = np.linalg.matrix_rank(l*F)
rslt2F = l*np.linalg.matrix_rank(F)
print(rslt1F,rslt2F)
print(rslt1F == rslt2F)

rslt1R = np.linalg.matrix_rank(l*R)
rslt2R = l*np.linalg.matrix_rank(R)
print(rslt1R,rslt2R)
print(rslt1R == rslt2R)

6 4.199999999999999
False
3 2.0999999999999996
False


### Rank of multiplied and summed matrices

In [132]:
m = 2
n = 5

A = np.random.randn(m,n)
B = np.random.randn(m,n)
AtA = A.T@A
BtB = B.T@B

rankA = np.linalg.matrix_rank(A) # r = 2
rankB = np.linalg.matrix_rank(B) # r = 2
rankAtA = np.linalg.matrix_rank(AtA) # r = 2
rankBtB = np.linalg.matrix_rank(BtB) # r = 2

AB = AtA@BtB 
AplusB = AtA + BtB 
rankAB = np.linalg.matrix_rank(AB) # r = 2
rankAplusB = np.linalg.matrix_rank(AplusB) # r = 4
print(rankA,rankB,rankAtA,rankBtB,rankAB,rankAplusB)

2 2 2 2 2 4


### Is this vector in the span of this set?

In [200]:
u = np.array([[1,2,3,4]]).T

s = np.array([[4,3,6,2],[0,4,0,1]]).T
t = np.array([[1,2,2,2],[0,0,1,2]]).T
v = np.concatenate((u,s),axis=1)
w = np.concatenate((u,t),axis=1)
print(s)
print(u)
print(w)
print(np.linalg.matrix_rank(s))
print(np.linalg.matrix_rank(t))
print(np.linalg.matrix_rank(v))
print(np.linalg.matrix_rank(w))

[[4 0]
 [3 4]
 [6 0]
 [2 1]]
[[1]
 [2]
 [3]
 [4]]
[[1 1 0]
 [2 2 0]
 [3 2 1]
 [4 2 2]]
2
2
3
2
