In [1]:
import numpy as np

In [3]:
m = 10
n = 3

X = np.random.randn(m,n)
y = np.random.randn(m,1)

In [21]:
Q,R = np.linalg.qr(X)

RtR = R.T@R
QRt = (Q@R).T
XtX = X.T@X
Xty = X.T@y

b = np.linalg.inv(RtR)@QRt@y
b2 = np.linalg.inv(XtX)@Xty
b3 = np.linalg.solve(RtR,QRt@y)
b4 = np.linalg.lstsq(X,y,rcond=None)[0]
print(b)
print(b2)
print(b3)
print(b4)

[[-0.18515451]
 [ 0.23105816]
 [-0.11687891]]
[[-0.18515451]
 [ 0.23105816]
 [-0.11687891]]
[[-0.18515451]
 [ 0.23105816]
 [-0.11687891]]
[[-0.18515451]
 [ 0.23105816]
 [-0.11687891]]
