In [1]:
import numpy as np

In [34]:
# Test some random MxN matrices wheter s(A+B) = sA + sB
a = 4
b = 2

M = np.random.randn(a,b)
N = np.random.randn(a,b)
l = .6
rslt1 = l*(M+N)
print(rslt1)
print(' ')
rslt2 = l*M + l*N
print(rslt2)
print(np.around(rslt1,decimals=10) == np.around(rslt2,decimals=10))
print(rslt1-rslt2)

[[ 0.11389524 -0.98437955]
 [ 0.78775749 -0.98180623]
 [ 3.02910504  1.60430741]
 [-0.92235181 -0.23153037]]
 
[[ 0.11389524 -0.98437955]
 [ 0.78775749 -0.98180623]
 [ 3.02910504  1.60430741]
 [-0.92235181 -0.23153037]]
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
[[5.55111512e-17 0.00000000e+00]
 [1.11022302e-16 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]]


In [30]:
print(rslt1[0,0])
print(rslt2[0,0])
print(np.around(1.23436,decimals=3))

-0.09178460768852065
-0.09178460768852065
1.234
